version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_service
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  pgbouncer:
    image: docker.io/bitnami/pgbouncer:1
    ports:
      - 6432:6432
    environment:
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT=5432
      - PGBOUNCER_AUTH_TYPE=md5
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=book_service
      - PGBOUNCER_DATABASE=book_service
      - PGBOUNCER_MAX_CLIENT_CONN=100
      - PGBOUNCER_IGNORE_STARTUP_PARAMETERS=extra_float_digits
volumes:
  postgresql_data:
    driver: local