// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: author.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthorClient is the client API for Author service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorClient interface {
	AuthorGet(ctx context.Context, in *AuthorGetRequest, opts ...grpc.CallOption) (*AuthorGetResponse, error)
	AuthorCreate(ctx context.Context, in *AuthorCreateRequest, opts ...grpc.CallOption) (*AuthorCreateResponse, error)
	AuthorList(ctx context.Context, in *AuthorListRequest, opts ...grpc.CallOption) (*AuthorListResponse, error)
	AuthorUpdate(ctx context.Context, in *AuthorUpdateRequest, opts ...grpc.CallOption) (*AuthorUpdateResponse, error)
	AuthorDelete(ctx context.Context, in *AuthorDeleteRequest, opts ...grpc.CallOption) (*AuthorDeleteResponse, error)
}

type authorClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorClient(cc grpc.ClientConnInterface) AuthorClient {
	return &authorClient{cc}
}

func (c *authorClient) AuthorGet(ctx context.Context, in *AuthorGetRequest, opts ...grpc.CallOption) (*AuthorGetResponse, error) {
	out := new(AuthorGetResponse)
	err := c.cc.Invoke(ctx, "/api.Author/AuthorGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorClient) AuthorCreate(ctx context.Context, in *AuthorCreateRequest, opts ...grpc.CallOption) (*AuthorCreateResponse, error) {
	out := new(AuthorCreateResponse)
	err := c.cc.Invoke(ctx, "/api.Author/AuthorCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorClient) AuthorList(ctx context.Context, in *AuthorListRequest, opts ...grpc.CallOption) (*AuthorListResponse, error) {
	out := new(AuthorListResponse)
	err := c.cc.Invoke(ctx, "/api.Author/AuthorList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorClient) AuthorUpdate(ctx context.Context, in *AuthorUpdateRequest, opts ...grpc.CallOption) (*AuthorUpdateResponse, error) {
	out := new(AuthorUpdateResponse)
	err := c.cc.Invoke(ctx, "/api.Author/AuthorUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorClient) AuthorDelete(ctx context.Context, in *AuthorDeleteRequest, opts ...grpc.CallOption) (*AuthorDeleteResponse, error) {
	out := new(AuthorDeleteResponse)
	err := c.cc.Invoke(ctx, "/api.Author/AuthorDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorServer is the server API for Author service.
// All implementations must embed UnimplementedAuthorServer
// for forward compatibility
type AuthorServer interface {
	AuthorGet(context.Context, *AuthorGetRequest) (*AuthorGetResponse, error)
	AuthorCreate(context.Context, *AuthorCreateRequest) (*AuthorCreateResponse, error)
	AuthorList(context.Context, *AuthorListRequest) (*AuthorListResponse, error)
	AuthorUpdate(context.Context, *AuthorUpdateRequest) (*AuthorUpdateResponse, error)
	AuthorDelete(context.Context, *AuthorDeleteRequest) (*AuthorDeleteResponse, error)
	mustEmbedUnimplementedAuthorServer()
}

// UnimplementedAuthorServer must be embedded to have forward compatible implementations.
type UnimplementedAuthorServer struct {
}

func (UnimplementedAuthorServer) AuthorGet(context.Context, *AuthorGetRequest) (*AuthorGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorGet not implemented")
}
func (UnimplementedAuthorServer) AuthorCreate(context.Context, *AuthorCreateRequest) (*AuthorCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorCreate not implemented")
}
func (UnimplementedAuthorServer) AuthorList(context.Context, *AuthorListRequest) (*AuthorListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorList not implemented")
}
func (UnimplementedAuthorServer) AuthorUpdate(context.Context, *AuthorUpdateRequest) (*AuthorUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorUpdate not implemented")
}
func (UnimplementedAuthorServer) AuthorDelete(context.Context, *AuthorDeleteRequest) (*AuthorDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorDelete not implemented")
}
func (UnimplementedAuthorServer) mustEmbedUnimplementedAuthorServer() {}

// UnsafeAuthorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorServer will
// result in compilation errors.
type UnsafeAuthorServer interface {
	mustEmbedUnimplementedAuthorServer()
}

func RegisterAuthorServer(s grpc.ServiceRegistrar, srv AuthorServer) {
	s.RegisterService(&Author_ServiceDesc, srv)
}

func _Author_AuthorGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorServer).AuthorGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Author/AuthorGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorServer).AuthorGet(ctx, req.(*AuthorGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Author_AuthorCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorServer).AuthorCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Author/AuthorCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorServer).AuthorCreate(ctx, req.(*AuthorCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Author_AuthorList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorServer).AuthorList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Author/AuthorList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorServer).AuthorList(ctx, req.(*AuthorListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Author_AuthorUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorServer).AuthorUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Author/AuthorUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorServer).AuthorUpdate(ctx, req.(*AuthorUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Author_AuthorDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorServer).AuthorDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Author/AuthorDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorServer).AuthorDelete(ctx, req.(*AuthorDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Author_ServiceDesc is the grpc.ServiceDesc for Author service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Author_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Author",
	HandlerType: (*AuthorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorGet",
			Handler:    _Author_AuthorGet_Handler,
		},
		{
			MethodName: "AuthorCreate",
			Handler:    _Author_AuthorCreate_Handler,
		},
		{
			MethodName: "AuthorList",
			Handler:    _Author_AuthorList_Handler,
		},
		{
			MethodName: "AuthorUpdate",
			Handler:    _Author_AuthorUpdate_Handler,
		},
		{
			MethodName: "AuthorDelete",
			Handler:    _Author_AuthorDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "author.proto",
}
