name: workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: book_service

    strategy:
      matrix:
        go: ['1.18']
    name: Run
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: make build
      - name: Linter
        run: make lint
      - name: Unit tests
        run: make test
      - name: Integration tests
        run: make goose-install && sh ./migrate-test.sh && make integration-test
