name: workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.18

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: book_service
          
    name: Run
    steps:
      - name: Build app
        run: make build
      - name: Linter
        run: make lint
      - name: Unit tests
        run: make test
      - name: Integration tests
        run: make goose-install && sh ./migrate-test.sh && make integration-test
        env:
          QA_DB_HOST: "postgres"
          QA_DB_PORT: "5432"
          QA_DB_USER: "test_user"
          QA_DB_PASSWORD: "test_password"
          QA_DB_NAME: "book_service"
